[package]
name = "oxide-skies"
version = "0.1.0"
authors = ["Neil McAlister <mcalistern@gmail.com>"]
build = "build.rs"

[dependencies]
hyper = "0.7.2"
serde = "0.7.0"
serde_json = "0.7.0"
filetime = "0.1"
time = "0.1"

[build-dependencies]
serde_codegen = "0.7.0"
syntex = "0.29.0"